const Order = require("../models/Order");

const escapeCsvValue = (value) => {
  if (value === null || value === undefined) {
    return "";
  }

  const stringValue = String(value);

  if (
    stringValue.includes(",") ||
    stringValue.includes('"') ||
    stringValue.includes("\n")
  ) {
    return `"${stringValue.replace(/"/g, '""')}"`;
  }

  return stringValue;
};

const getOrderSummary = (items = []) => {
  return items
    .map((item) => `${item.productName} x${item.quantity}`)
    .join(", ");
};

const buildDateRangeFilter = (startDate, endDate) => {
  if (!startDate && !endDate) {
    return {};
  }

  const filter = {};

  if (startDate) {
    filter.$gte = new Date(startDate);
  }

  if (endDate) {
    const end = new Date(endDate);
    end.setHours(23, 59, 59, 999);
    filter.$lte = end;
  }

  return filter;
};

const buildExportFileName = (startDate, endDate) => {
  if (startDate && endDate) {
    return `Orders_Payments_${startDate}_to_${endDate}.csv`;
  }

  if (startDate) {
    return `Orders_Payments_from_${startDate}.csv`;
  }

  if (endDate) {
    return `Orders_Payments_through_${endDate}.csv`;
  }

  return "Orders_Payments_All.csv";
};

const generateOrdersPaymentsCsv = async (req, res) => {
  try {
    const { startDate, endDate } = req.query;
    const generatedAt = new Date().toISOString();
    const generator = "Express";

    const query = {
      ownerId: req.user._id
    };

    const orderDateFilter = buildDateRangeFilter(startDate, endDate);

    if (Object.keys(orderDateFilter).length > 0) {
      query.orderDate = orderDateFilter;
    }

    const orders = await Order.find(query)
      .populate("customerId", "name email phone")
      .sort({ orderDate: -1 });

    const rows = [];

    rows.push(["Home Gig Orders and Payments Export"]);
    rows.push(["Generated By", generator]);
    rows.push(["Generated At", generatedAt]);
    rows.push([]);

    rows.push([
      "Order #",
      "Customer",
      "Customer Email",
      "Order Date",
      "Order Summary",
      "Total",
      "Payment Status",
      "Payment Date"
    ]);

    orders.forEach((order) => {
      rows.push([
        order.orderNumber,
        order.customerId?.name || "",
        order.customerId?.email || "",
        order.orderDate ? order.orderDate.toISOString() : "",
        getOrderSummary(order.items),
        order.orderTotal,
        order.paymentStatus,
        order.paymentDate ? order.paymentDate.toISOString() : ""
      ]);
    });

    const csvContent = rows
      .map((row) => row.map(escapeCsvValue).join(","))
      .join("\n");

    const fileName = buildExportFileName(startDate, endDate);

    res.setHeader("Content-Type", "text/csv");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${fileName}"`
    );

    res.status(200).send(csvContent);
  } catch (error) {
    res.status(500).json({
      message: "Failed to generate CSV export",
      error: error.message
    });
  }
};

module.exports = {
  generateOrdersPaymentsCsv
};