const Order = require("../models/Order");

const escapeCsvValue = (value) => {
  if (value === null || value === undefined) {
    return "";
  }

  const stringValue = String(value);

  if (
    stringValue.includes(",") ||
    stringValue.includes('"') ||
    stringValue.includes("\n")
  ) {
    return `"${stringValue.replace(/"/g, '""')}"`;
  }

  return stringValue;
};

const getOrderSummary = (items = []) => {
  return items
    .map((item) => `${item.productName} x${item.quantity}`)
    .join(", ");
};

const generateOrdersPaymentsCsv = async (req, res) => {
  try {
    const generatedAt = new Date().toISOString();
    const generator = "Express";

    const orders = await Order.find({
      ownerId: req.user._id
    })
      .populate("customerId", "name email phone")
      .sort({ orderDate: -1 });

    const rows = [];

    rows.push(["Home Gig Orders and Payments Export"]);
    rows.push(["Generated By", generator]);
    rows.push(["Generated At", generatedAt]);
    rows.push([]);

    rows.push([
      "Order #",
      "Customer",
      "Customer Email",
      "Order Date",
      "Order Summary",
      "Total",
      "Payment Status",
      "Payment Date"
    ]);

    orders.forEach((order) => {
      rows.push([
        order.orderNumber,
        order.customerId?.name || "",
        order.customerId?.email || "",
        order.orderDate ? order.orderDate.toISOString() : "",
        getOrderSummary(order.items),
        order.orderTotal,
        order.paymentStatus,
        order.paymentDate ? order.paymentDate.toISOString() : ""
      ]);
    });

    const csvContent = rows
      .map((row) => row.map(escapeCsvValue).join(","))
      .join("\n");

    const fileName = `orders_payments_${Date.now()}.csv`;

    res.setHeader("Content-Type", "text/csv");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${fileName}"`
    );

    res.status(200).send(csvContent);
  } catch (error) {
    res.status(500).json({
      message: "Failed to generate CSV export",
      error: error.message
    });
  }
};

module.exports = {
  generateOrdersPaymentsCsv
};