const Order = require("../models/Order");
const Payment = require("../models/Payment");

const escapeCsvValue = (value) => {
  if (value === null || value === undefined) {
    return "";
  }

  const stringValue = String(value);

  if (
    stringValue.includes(",") ||
    stringValue.includes('"') ||
    stringValue.includes("\n")
  ) {
    return `"${stringValue.replace(/"/g, '""')}"`;
  }

  return stringValue;
};

const generateOrdersPaymentsCsv = async (req, res) => {
  try {
    const generatedAt = new Date().toISOString();
    const generator = "Express";

    const orders = await Order.find({
      ownerId: req.user._id
    })
      .populate("customerId", "name email phone")
      .sort({ orderDate: -1 });

    const payments = await Payment.find({
      ownerId: req.user._id
    })
      .populate("customerId", "name email phone")
      .populate("orderId", "orderDate orderTotal paymentStatus")
      .sort({ paymentDate: -1 });

    const rows = [];

    rows.push(["Home Gig Orders and Payments Export"]);
    rows.push(["Generated By", generator]);
    rows.push(["Generated At", generatedAt]);
    rows.push([]);

    rows.push(["ORDERS"]);
    rows.push([
      "Order ID",
      "Customer",
      "Customer Email",
      "Order Date",
      "Order Total",
      "Payment Status",
      "Order Source",
      "Notes"
    ]);

    orders.forEach((order) => {
      rows.push([
        order._id,
        order.customerId?.name || "",
        order.customerId?.email || "",
        order.orderDate ? order.orderDate.toISOString() : "",
        order.orderTotal,
        order.paymentStatus,
        order.orderSource,
        order.notes || ""
      ]);
    });

    rows.push([]);
    rows.push(["PAYMENTS"]);
    rows.push([
      "Payment ID",
      "Order ID",
      "Customer",
      "Customer Email",
      "Payment Date",
      "Amount Paid",
      "Payment Method",
      "Payment Status",
      "Notes"
    ]);

    payments.forEach((payment) => {
      rows.push([
        payment._id,
        payment.orderId?._id || payment.orderId || "",
        payment.customerId?.name || "",
        payment.customerId?.email || "",
        payment.paymentDate ? payment.paymentDate.toISOString() : "",
        payment.amountPaid,
        payment.paymentMethod,
        payment.paymentStatus,
        payment.notes || ""
      ]);
    });

    const csvContent = rows
      .map((row) => row.map(escapeCsvValue).join(","))
      .join("\n");

    const fileName = `orders_payments_${Date.now()}.csv`;

    res.setHeader("Content-Type", "text/csv");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${fileName}"`
    );

    res.status(200).send(csvContent);
  } catch (error) {
    res.status(500).json({
      message: "Failed to generate CSV export",
      error: error.message
    });
  }
};

module.exports = {
  generateOrdersPaymentsCsv
};